#!/bin/bash

# This script removes the intermediate files generated by nextflow stages on the
# rnaseq and small rna datasets.

# These intermediate files are not tracked by dvc to save space, but are not removed
# at the end of the corresponding stage, in case we want to explore other nextflow
# parameters

rm -rf "datasets/consortium/human-datasets/02_organized_data/rnaseq/nf-rnaseq/work"
rm -rf "datasets/consortium/SOD1-mouse/02_organized_data/rnaseq/nf-rnaseq/work"
rm -rf "datasets/consortium/TDP43-mouse/02_organized_data/rnaseq/nf-rnaseq/work"
rm -rf "datasets/consortium/C9orf72-mouse/02_organized_data/rnaseq/nf-rnaseq/work"
rm -rf "datasets/consortium/FUS-mouse/02_organized_data/rnaseq/nf-rnaseq/work"



rm -rf "datasets/consortium/FUS-mouse/02_organized_data/srna/nf-smrna/work"
rm -rf "datasets/consortium/SOD1-mouse/02_organized_data/srna/nf-smrna/work"
rm -rf "datasets/consortium/TDP43-mouse/02_organized_data/srna/nf-smrna/work"
rm -rf "datasets/consortium/C9orf72-mouse/02_organized_data/srna/nf-smrna/work"
rm -rf "datasets/consortium/human-datasets/02_organized_data/srna/nf-smrna/work"

